//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public person()
        {
            this.person1 = new HashSet<person>();
        }
    
        public long id { get; set; }
        public int Serial { get; set; }
        public string SSNumber { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Sex { get; set; }
        public string FamilySituation { get; set; }
        public short NbChildren { get; set; }
        public string Phone { get; set; }
        public string PersonalMail { get; set; }
        public string Adress { get; set; }
        public string AdditionalAddress { get; set; }
        public string PostalCode { get; set; }
        public string Town { get; set; }
        public System.DateTime StartingDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string Profile { get; set; }
        public string CompanyMail { get; set; }
        public string CompanyPassword { get; set; }
        public string AnnualInterviewDate { get; set; }
        public string TrialPeriodStatus { get; set; }
        public float VacationAquired { get; set; }
        public float VacationTaken { get; set; }
        public float VacationRemaining { get; set; }
        public float VacationToAquire { get; set; }
        public float VacationRemainingFromLastYear { get; set; }
        public float RTTAcquired { get; set; }
        public float RTTTaken { get; set; }
        public float RTTRemainig { get; set; }
        public float RTTToAquire { get; set; }
        public float RTTRemainingFromLastYear { get; set; }
        public Nullable<long> ResponsibleId { get; set; }
        public string AspNetUserId { get; set; }
        public string CompanyPhone { get; set; }
        public Nullable<System.DateTime> LastConnexion { get; set; }
    
        public virtual aspnetusers aspnetusers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<person> person1 { get; set; }
        public virtual person person2 { get; set; }
    }
}
